  const response = [
    {
      'name': 'Cut',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'Temp',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'Pol',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'CNC',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'IG',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'Lami',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'Span',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'Creating',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
    },
    {
      'name': 'Loading',
      'week1' : 2.1,
      'week2' : 3.1,
      'week3': 4.1,
      'week4': 8.2,
      },
  ]
